### ISSUE TITLE
When fixable rules are overlapping, It takes multiple format/fix commands to reach the same result as cli xo --fix

### ISSUE THREAD

**Issue by gutenye** [xojs/vscode-linter-xo#113] opened 2022-05-26 14:24 UTC
The .xo-config.cjs

Using [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort)

```js
// yarn add --dev eslint-config-simple-import-sort
module.exports = {
  prettier: true,
  plugins: ['simple-import-sort'],
  rules: {		
    'simple-import-sort/imports': 'error'
  }
}
```

This code

```
import {b,a} from 'file'
```

is formatted into below using VSCode  `Format Document with - XO`

```
import {a,b} from 'file'
```

is formatted into below using Cmd `xo --fix`

```
import { a, b } from 'file'
```

The result is different.

I guess the Cmd runs `eslint fix -> prettier` in order, but the VSCode runs `eslint fix` only.

**Comment by Spence-S** [comment] 2022-05-26 17:58
The extensions does not run things any differently than the CLI. There is no prettier or eslint step, they are both ran at the same time by eslint under the hood in xo. 

1) Try setting the  "xo.runtime" setting in VSCode so you are using the same nodejs binary for both the cli and the extension. Otherwise, by default xo in vscode will use the version of nodejs bundled inside of vscode which can cause different results from the cli. 

2) Make sure you have all other extensions disabled. 

Please let me know if this fixes the issue.

**Comment by gutenye** [comment] 2022-05-27 02:08
Setting the `xo.runtime` didn't help. I output the [edits and result](https://github.com/xojs/vscode-linter-xo/blob/736f91e6442ebbb80930d3e2d3a9e94e8183d24b/server/server.js#L740-L745) and find out the problem

```js
"edits": {
   "[0,0,0,21]-simple-import-sort/imports": {
      "label": "Fix this simple-import-sort/imports problem",
      "documentVersion": 13,
      "ruleId": "simple-import-sort/imports",
      "edit": {
        "range": [ 0, 21 ],
        "text": "import {a,b} from 'a'"
      }
    },
    "[0,8,0,11]-prettier/prettier": {
      "label": "Fix this prettier/prettier problem",
      "documentVersion": 13,
      "ruleId": "prettier/prettier",
      "edit": {
        "range": [ 8, 11],
        "text": " b, a "
      }
    },
"result": {
    "documentVersion": 13,
    "edits": [
      {
        "range": { "start": { "line": 0, "character": 0 }, "end": { "line": 0, "character": 21 }
        },
        "newText": "import {a,b} from 'a'"
      }
    ]
  }
```

The VSCode runs the fix at the same time and output an overlap free result. I guess the xo cmd runs the fix in sequence.

**Comment by Spence-S** [comment] 2022-05-27 12:23
@gutenye - thank you so much for digging into this problem. I will look more deeply into this and see if I need to strip out some of the old overlap logic.

**Comment by Spence-S** [comment] 2022-05-28 16:10
So after taking a look I realized that this is just a known issue. There is actually not a core problem, you just have to run format 2x to get the same results as the CLI for some overlapping rules. This is something I am interested in fixing long term, but it's not a very high priority since the work around is just executing format 2x. 

This is a duplicate of https://github.com/xojs/vscode-linter-xo/issues/42 

Unfortunately, solving this issue is not as trivial as "run x before y" - we will need to recreate the same logic that eslint already uses to handle cases where a single line has overlapping fixes and I believe it's complicated. 

I will keep this open until I have time to fix, but this will likely remain a low priority since its a very minor inconvenience and the extension still gets to the same final result after a couple of format commands.

**Comment by gutenye** [comment] 2022-06-01 09:55
Will this solution be easier? Add a `editor.codeActionsOnSave` option.

The Eslint VSCode Exension has [this option](https://github.com/Microsoft/vscode-eslint#version-204)

```
 "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
  },
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
 ```

This will run eslint fix first, then prettier fix, fixes my issue.

**Comment by Spence-S** [comment] 2022-06-01 12:29
> Save two or more times is not an option for me, every time I save a file, I have to take extra time to check if there's still eslint error? If so, save it again, if not, skip it. It's slow and not developer-friendly.

eslint suffers from this too, but is admittedly a little better than this xo extension --- try formatting big unformatted files with eslint, xo + unicorn plugins and prettier. -- You will have to save multiple times. Also, it doesn't happen very often in this extension at all, it is not nearly as inconvenient as you are making it out to be.

> Will this solution be easier? Add a editor.codeActionsOnSave option.

Maybe - this is on the road map. I have recently started supporting code actions, but I haven't done the code actions on save. Feel free to take a look at the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) and implement this.

> Another idea, can we change

Feel free to test this out! I will play with this idea. My suspicion is that this will not work well at all because it will cause the squiggly error underlines in vscode to be in the wrong places, or results won't return all the correct information for the original errors, so it will be missing errors and flagging the wrong places. The `lint` functionality is more important than the format functionality. - If this were to work and be this simple the that would be great!... However, I am not optimistic until I see and test it.

Note that every lint error already has the "fixed" result in it, if it is fixable, even without the "fix" option. The likely only way to really fix this is to manually implement logic in `getDocumentFixes` method. 

And please trust me that I have attempted to fix this problem on numerous occasions because I do know it is annoying when it happens, but I haven't found an easy way yet.

I do accept PRs, although I have only got 1 I think since taking over maintenance of this extension.

**Comment by Spence-S** [comment] 2022-09-19 23:19
Was able to get it working in the latest release so that this should no longer occur, thanks for the suggestions

**Closed by Spence-S** 2022-09-19 23:19 UTC
